env: standard
runtime: nodejs16
instance_class: F1
service: default
inbound_services:
- warmup
automatic_scaling:
    max_idle_instances: 1
    max_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto
